In [ ]:
from google.colab import files

uploaded = files.upload()

Saving Global temperature anomalies dataset.csv to Global temperature anomalies dataset.csv

In [ ]:
import pandas as pd

filename = list(uploaded.keys())[0]

df = pd.read_csv(filename)

print("Dataset uploaded and loaded successfully!")
print("Shape:", df.shape)

display(df.head())

Dataset uploaded and loaded successfully!
Shape: (100000, 26)

,Country,Year,Temperature_Anomaly,CO2_Emissions,Population,Forest_Area,GDP,Renewable_Energy_Usage,Methane_Emissions,Sea_Level_Rise,...,Waste_Management,Per_Capita_Emissions,Industrial_Activity,Air_Pollution_Index,Biodiversity_Index,Ocean_Acidification,Fossil_Fuel_Usage,Energy_Consumption_Per_Capita,Policy_Score,Average_Temperature
0,Country_103,1913,-1.163537,8.876061e+08,1.627978e+08,54.872178,6.139887e+12,76.710013,8.317626e+06,8.111839,...,82.691409,2.285351,4.060975,150.285539,90.073356,8.025470,39.163860,1480.164332,78.870012,20.825292
1,Country_180,1950,-0.432122,4.497517e+08,4.281359e+08,84.051006,2.601447e+12,68.450021,6.206540e+06,42.025915,...,59.322883,17.411668,85.300604,27.305922,88.289837,8.021719,28.252554,1482.730048,32.600905,28.720587
2,Country_93,2014,0.444954,4.579080e+08,4.926732e+08,72.295357,5.192677e+12,36.725699,1.056885e+06,20.953840,...,94.982931,12.039703,83.804880,216.911429,86.936256,7.647408,61.548382,706.918809,37.671300,15.014084
3,Country_15,2020,-1.171616,5.049503e+08,1.252169e+09,17.259684,8.252128e+12,77.547901,1.986813e+06,45.599595,...,62.064250,2.853957,47.014265,35.869182,44.904331,7.569353,82.423750,2616.238324,86.581725,-1.277086
4,Country_107,1964,-0.564038,6.898891e+08,2.932960e+08,44.438605,8.560746e+12,10.019576,3.313252e+06,7.652150,...,84.431279,19.801173,89.379613,284.263093,8.102916,8.015415,29.964450,4975.683780,20.618406,2.861989

In [ ]:
print(df.dtypes)

Country                           object
Year                               int64
Temperature_Anomaly              float64
CO2_Emissions                    float64
Population                       float64
Forest_Area                      float64
GDP                              float64
Renewable_Energy_Usage           float64
Methane_Emissions                float64
Sea_Level_Rise                   float64
Arctic_Ice_Extent                float64
Urbanization                     float64
Deforestation_Rate               float64
Extreme_Weather_Events             int64
Average_Rainfall                 float64
Solar_Energy_Potential           float64
Waste_Management                 float64
Per_Capita_Emissions             float64
Industrial_Activity              float64
Air_Pollution_Index              float64
Biodiversity_Index               float64
Ocean_Acidification              float64
Fossil_Fuel_Usage                float64
Energy_Consumption_Per_Capita    float64
Policy_Score                     float64
Average_Temperature              float64
dtype: object

In [ ]:
missing = df.isnull().sum()

print(missing)

Country                             0
Year                                0
Temperature_Anomaly                 0
CO2_Emissions                       0
Population                          0
Forest_Area                         0
GDP                                 0
Renewable_Energy_Usage              0
Methane_Emissions                   0
Sea_Level_Rise                      0
Arctic_Ice_Extent                   0
Urbanization                        0
Deforestation_Rate                  0
Extreme_Weather_Events              0
Average_Rainfall                    0
Solar_Energy_Potential              0
Waste_Management                    0
Per_Capita_Emissions                0
Industrial_Activity                 0
Air_Pollution_Index                 0
Biodiversity_Index               2000
Ocean_Acidification              2000
Fossil_Fuel_Usage                2000
Energy_Consumption_Per_Capita    2000
Policy_Score                     2000
Average_Temperature              2000
dtype: int64

In [ ]:
missing_table = pd.DataFrame({
      "Column": df.columns,
          "Missing_Values": df.isnull().sum().values,
              "Missing_Percentage": (
                      df.isnull().sum().values / len(df) * 100
                          )
                          })
display(
                              missing_table.sort_values(
                                      "Missing_Values",
                                              ascending=False
                                                  )
                                                  )

                           Column  Missing_Values  Missing_Percentage
23  Energy_Consumption_Per_Capita            2000                 2.0
22              Fossil_Fuel_Usage            2000                 2.0
24                   Policy_Score            2000                 2.0
25            Average_Temperature            2000                 2.0
21            Ocean_Acidification            2000                 2.0
20             Biodiversity_Index            2000                 2.0
2             Temperature_Anomaly               0                 0.0
3                   CO2_Emissions               0                 0.0
0                         Country               0                 0.0
1                            Year               0                 0.0
9                  Sea_Level_Rise               0                 0.0
8               Methane_Emissions               0                 0.0
7          Renewable_Energy_Usage               0                 0.0
6                             GDP               0                 0.0
5                     Forest_Area               0                 0.0
4                      Population               0                 0.0
10              Arctic_Ice_Extent               0                 0.0
11                   Urbanization               0                 0.0
17           Per_Capita_Emissions               0                 0.0
16               Waste_Management               0                 0.0
15         Solar_Energy_Potential               0                 0.0
14               Average_Rainfall               0                 0.0
13         Extreme_Weather_Events               0                 0.0
12             Deforestation_Rate               0                 0.0
18            Industrial_Activity               0                 0.0
19            Air_Pollution_Index               0                 0.0

In [ ]:
print("Number of duplicate rows:")
print(df.duplicated().sum())

Number of duplicate rows:
0

In [ ]:
for column in df.columns:
      print("\n", column)
      print("Unique values:", df[column].nunique())

 Country
Unique values: 195

 Year
Unique values: 124

 Temperature_Anomaly
Unique values: 100000

 CO2_Emissions
Unique values: 100000

 Population
Unique values: 100000

 Forest_Area
Unique values: 100000

 GDP
Unique values: 100000

 Renewable_Energy_Usage
Unique values: 100000

 Methane_Emissions
Unique values: 100000

 Sea_Level_Rise
Unique values: 100000

 Arctic_Ice_Extent
Unique values: 100000

 Urbanization
Unique values: 100000

 Deforestation_Rate
Unique values: 100000

 Extreme_Weather_Events
Unique values: 50

 Average_Rainfall
Unique values: 100000

 Solar_Energy_Potential
Unique values: 100000

 Waste_Management
Unique values: 100000

 Per_Capita_Emissions
Unique values: 100000

 Industrial_Activity
Unique values: 100000

 Air_Pollution_Index
Unique values: 100000

 Biodiversity_Index
Unique values: 98000

 Ocean_Acidification
Unique values: 98000

 Fossil_Fuel_Usage
Unique values: 98000

 Energy_Consumption_Per_Capita
Unique values: 98000

 Policy_Score
Unique values: 98000

 Average_Temperature
Unique values: 98000

In [ ]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Country,100000,195,Country_186,557,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Year,100000.0,NaN,NaN,NaN,1961.4221,35.758799,1900.0,1930.0,1961.0,1992.0,2023.0
Temperature_Anomaly,100000.0,NaN,NaN,NaN,0.002647,1.154579,-1.999981,-0.999449,0.003523,0.998067,1.999958
CO2_Emissions,100000.0,NaN,NaN,NaN,500700691.133061,288738792.383064,102227.072978,250422329.450305,500676918.882193,750631819.483133,999979263.4925
Population,100000.0,NaN,NaN,NaN,750197277.004476,432870867.379048,1013054.487672,376254469.379589,749921199.947228,1125222043.61546,1499991919.275
Forest_Area,100000.0,NaN,NaN,NaN,50.01241,28.806287,0.000052,24.960397,50.141257,74.898296,99.999831
GDP,100000.0,NaN,NaN,NaN,4995923420626.767578,2883116738134.616699,152473661.806325,2507502960030.70459,4985849419161.166992,7489082310968.15332,9999894320410.578125
Renewable_Energy_Usage,100000.0,NaN,NaN,NaN,50.115658,28.84149,0.005306,25.302244,50.011581,75.095944,99.999493
Methane_Emissions,100000.0,NaN,NaN,NaN,5003712.703855,2887606.479931,1133.254071,2501312.432703,4997724.458143,7507854.679103,9999928.178529
Sea_Level_Rise,100000.0,NaN,NaN,NaN,22.568046,15.908163,-4.999954,8.739127,22.728423,36.33315,49.99768
Arctic_Ice_Extent,100000.0,NaN,NaN,NaN,8.003934,4.03913,1.000036,4.504867,7.999331,11.499503,14.999878
Urbanization,100000.0,NaN,NaN,NaN,49.918763,28.845952,0.000051,24.990116,49.782236,74.859595,99.999778
Deforestation_Rate,100000.0,NaN,NaN,NaN,2.494102,1.441101,0.000063,1.242782,2.488219,3.742646,4.99996
Extreme_Weather_Events,100000.0,NaN,NaN,NaN,24.51986,14.44272,0.0,12.0,25.0,37.0,49.0
Average_Rainfall,100000.0,NaN,NaN,NaN,2750.708213,1295.030843,500.014534,1633.90115,2750.194388,3872.37867,4999.820614
Solar_Energy_Potential,100000.0,NaN,NaN,NaN,1496.45322,576.483698,500.020868,997.265549,1497.830588,1994.096815,2499.98137
Waste_Management,100000.0,NaN,NaN,NaN,50.009789,28.89085,0.000038,25.114615,49.903504,75.072693,99.999938
Per_Capita_Emissions,100000.0,NaN,NaN,NaN,9.969773,5.757802,0.000402,5.020629,9.921851,14.958753,19.999826
Industrial_Activity,100000.0,NaN,NaN,NaN,50.103537,28.913039,0.002979,25.062131,50.120981,75.279997,99.999127
Air_Pollution_Index,100000.0,NaN,NaN,NaN,149.627677,86.599662,0.001419,74.727558,149.508132,224.633077,299.992559
Biodiversity_Index,98000.0,NaN,NaN,NaN,49.981122,28.863991,0.001155,24.93738,50.097524,74.813613,99.999568
Ocean_Acidification,98000.0,NaN,NaN,NaN,8.000386,0.288655,7.500007,7.750257,8.001393,8.249049,8.499991
Fossil_Fuel_Usage,98000.0,NaN,NaN,NaN,49.997963,28.900204,0.000688,24.962573,50.012808,75.078507,99.999789
Energy_Consumption_Per_Capita,98000.0,NaN,NaN,NaN,2547.993027,1416.496311,100.031306,1320.219583,2546.61643,3775.097658,4999.981227
Policy_Score,98000.0,NaN,NaN,NaN,49.988004,28.837057,0.003098,25.023471,49.957149,74.900395,99.999622
Average_Temperature,98000.0,NaN,NaN,NaN,15.033006,14.430887,-9.99995,2.56978,15.0321,27.524841,39.998836

In [ ]:
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
Year,100000.0,1.961422e+03,3.575880e+01,1.900000e+03,1.930000e+03,1.961000e+03,1.992000e+03,2.023000e+03
Temperature_Anomaly,100000.0,2.647292e-03,1.154579e+00,-1.999981e+00,-9.994490e-01,3.523434e-03,9.980670e-01,1.999958e+00
CO2_Emissions,100000.0,5.007007e+08,2.887388e+08,1.022271e+05,2.504223e+08,5.006769e+08,7.506318e+08,9.999793e+08
Population,100000.0,7.501973e+08,4.328709e+08,1.013054e+06,3.762545e+08,7.499212e+08,1.125222e+09,1.499992e+09
Forest_Area,100000.0,5.001241e+01,2.880629e+01,5.188446e-05,2.496040e+01,5.014126e+01,7.489830e+01,9.999983e+01
GDP,100000.0,4.995923e+12,2.883117e+12,1.524737e+08,2.507503e+12,4.985849e+12,7.489082e+12,9.999894e+12
Renewable_Energy_Usage,100000.0,5.011566e+01,2.884149e+01,5.306081e-03,2.530224e+01,5.001158e+01,7.509594e+01,9.999949e+01
Methane_Emissions,100000.0,5.003713e+06,2.887606e+06,1.133254e+03,2.501312e+06,4.997724e+06,7.507855e+06,9.999928e+06
Sea_Level_Rise,100000.0,2.256805e+01,1.590816e+01,-4.999954e+00,8.739127e+00,2.272842e+01,3.633315e+01,4.999768e+01
Arctic_Ice_Extent,100000.0,8.003934e+00,4.039130e+00,1.000036e+00,4.504867e+00,7.999331e+00,1.149950e+01,1.499988e+01
Urbanization,100000.0,4.991876e+01,2.884595e+01,5.058923e-05,2.499012e+01,4.978224e+01,7.485959e+01,9.999978e+01
Deforestation_Rate,100000.0,2.494102e+00,1.441101e+00,6.268523e-05,1.242782e+00,2.488219e+00,3.742646e+00,4.999960e+00
Extreme_Weather_Events,100000.0,2.451986e+01,1.444272e+01,0.000000e+00,1.200000e+01,2.500000e+01,3.700000e+01,4.900000e+01
Average_Rainfall,100000.0,2.750708e+03,1.295031e+03,5.000145e+02,1.633901e+03,2.750194e+03,3.872379e+03,4.999821e+03
Solar_Energy_Potential,100000.0,1.496453e+03,5.764837e+02,5.000209e+02,9.972655e+02,1.497831e+03,1.994097e+03,2.499981e+03
Waste_Management,100000.0,5.000979e+01,2.889085e+01,3.774576e-05,2.511462e+01,4.990350e+01,7.507269e+01,9.999994e+01
Per_Capita_Emissions,100000.0,9.969773e+00,5.757802e+00,4.018352e-04,5.020629e+00,9.921851e+00,1.495875e+01,1.999983e+01
Industrial_Activity,100000.0,5.010354e+01,2.891304e+01,2.978661e-03,2.506213e+01,5.012098e+01,7.528000e+01,9.999913e+01
Air_Pollution_Index,100000.0,1.496277e+02,8.659966e+01,1.419316e-03,7.472756e+01,1.495081e+02,2.246331e+02,2.999926e+02
Biodiversity_Index,98000.0,4.998112e+01,2.886399e+01,1.155204e-03,2.493738e+01,5.009752e+01,7.481361e+01,9.999957e+01
Ocean_Acidification,98000.0,8.000386e+00,2.886549e-01,7.500007e+00,7.750257e+00,8.001393e+00,8.249049e+00,8.499991e+00
Fossil_Fuel_Usage,98000.0,4.999796e+01,2.890020e+01,6.882267e-04,2.496257e+01,5.001281e+01,7.507851e+01,9.999979e+01
Energy_Consumption_Per_Capita,98000.0,2.547993e+03,1.416496e+03,1.000313e+02,1.320220e+03,2.546616e+03,3.775098e+03,4.999981e+03
Policy_Score,98000.0,4.998800e+01,2.883706e+01,3.097640e-03,2.502347e+01,4.995715e+01,7.490039e+01,9.999962e+01
Average_Temperature,98000.0,1.503301e+01,1.443089e+01,-9.999950e+00,2.569780e+00,1.503210e+01,2.752484e+01,3.999884e+01

In [ ]:
display(df.describe().T)

,count,mean,std,min,25%,50%,75%,max
Year,100000.0,1.961422e+03,3.575880e+01,1.900000e+03,1.930000e+03,1.961000e+03,1.992000e+03,2.023000e+03
Temperature_Anomaly,100000.0,2.647292e-03,1.154579e+00,-1.999981e+00,-9.994490e-01,3.523434e-03,9.980670e-01,1.999958e+00
CO2_Emissions,100000.0,5.007007e+08,2.887388e+08,1.022271e+05,2.504223e+08,5.006769e+08,7.506318e+08,9.999793e+08
Population,100000.0,7.501973e+08,4.328709e+08,1.013054e+06,3.762545e+08,7.499212e+08,1.125222e+09,1.499992e+09
Forest_Area,100000.0,5.001241e+01,2.880629e+01,5.188446e-05,2.496040e+01,5.014126e+01,7.489830e+01,9.999983e+01
GDP,100000.0,4.995923e+12,2.883117e+12,1.524737e+08,2.507503e+12,4.985849e+12,7.489082e+12,9.999894e+12
Renewable_Energy_Usage,100000.0,5.011566e+01,2.884149e+01,5.306081e-03,2.530224e+01,5.001158e+01,7.509594e+01,9.999949e+01
Methane_Emissions,100000.0,5.003713e+06,2.887606e+06,1.133254e+03,2.501312e+06,4.997724e+06,7.507855e+06,9.999928e+06
Sea_Level_Rise,100000.0,2.256805e+01,1.590816e+01,-4.999954e+00,8.739127e+00,2.272842e+01,3.633315e+01,4.999768e+01
Arctic_Ice_Extent,100000.0,8.003934e+00,4.039130e+00,1.000036e+00,4.504867e+00,7.999331e+00,1.149950e+01,1.499988e+01
Urbanization,100000.0,4.991876e+01,2.884595e+01,5.058923e-05,2.499012e+01,4.978224e+01,7.485959e+01,9.999978e+01
Deforestation_Rate,100000.0,2.494102e+00,1.441101e+00,6.268523e-05,1.242782e+00,2.488219e+00,3.742646e+00,4.999960e+00
Extreme_Weather_Events,100000.0,2.451986e+01,1.444272e+01,0.000000e+00,1.200000e+01,2.500000e+01,3.700000e+01,4.900000e+01
Average_Rainfall,100000.0,2.750708e+03,1.295031e+03,5.000145e+02,1.633901e+03,2.750194e+03,3.872379e+03,4.999821e+03
Solar_Energy_Potential,100000.0,1.496453e+03,5.764837e+02,5.000209e+02,9.972655e+02,1.497831e+03,1.994097e+03,2.499981e+03
Waste_Management,100000.0,5.000979e+01,2.889085e+01,3.774576e-05,2.511462e+01,4.990350e+01,7.507269e+01,9.999994e+01
Per_Capita_Emissions,100000.0,9.969773e+00,5.757802e+00,4.018352e-04,5.020629e+00,9.921851e+00,1.495875e+01,1.999983e+01
Industrial_Activity,100000.0,5.010354e+01,2.891304e+01,2.978661e-03,2.506213e+01,5.012098e+01,7.528000e+01,9.999913e+01
Air_Pollution_Index,100000.0,1.496277e+02,8.659966e+01,1.419316e-03,7.472756e+01,1.495081e+02,2.246331e+02,2.999926e+02
Biodiversity_Index,98000.0,4.998112e+01,2.886399e+01,1.155204e-03,2.493738e+01,5.009752e+01,7.481361e+01,9.999957e+01
Ocean_Acidification,98000.0,8.000386e+00,2.886549e-01,7.500007e+00,7.750257e+00,8.001393e+00,8.249049e+00,8.499991e+00
Fossil_Fuel_Usage,98000.0,4.999796e+01,2.890020e+01,6.882267e-04,2.496257e+01,5.001281e+01,7.507851e+01,9.999979e+01
Energy_Consumption_Per_Capita,98000.0,2.547993e+03,1.416496e+03,1.000313e+02,1.320220e+03,2.546616e+03,3.775098e+03,4.999981e+03
Policy_Score,98000.0,4.998800e+01,2.883706e+01,3.097640e-03,2.502347e+01,4.995715e+01,7.490039e+01,9.999962e+01
Average_Temperature,98000.0,1.503301e+01,1.443089e+01,-9.999950e+00,2.569780e+00,1.503210e+01,2.752484e+01,3.999884e+01

In [ ]:
df.shape

(100000, 26)

In [ ]:
df.dtypes

Country                           object
Year                               int64
Temperature_Anomaly              float64
CO2_Emissions                    float64
Population                       float64
Forest_Area                      float64
GDP                              float64
Renewable_Energy_Usage           float64
Methane_Emissions                float64
Sea_Level_Rise                   float64
Arctic_Ice_Extent                float64
Urbanization                     float64
Deforestation_Rate               float64
Extreme_Weather_Events             int64
Average_Rainfall                 float64
Solar_Energy_Potential           float64
Waste_Management                 float64
Per_Capita_Emissions             float64
Industrial_Activity              float64
Air_Pollution_Index              float64
Biodiversity_Index               float64
Ocean_Acidification              float64
Fossil_Fuel_Usage                float64
Energy_Consumption_Per_Capita    float64
Policy_Score                     float64
Average_Temperature              float64
dtype: object

In [ ]:
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

print("\nColumn names:")
print(df.columns.tolist())

Number of rows: 100000
Number of columns: 26

Column names:
['Country', 'Year', 'Temperature_Anomaly', 'CO2_Emissions', 'Population', 'Forest_Area', 'GDP', 'Renewable_Energy_Usage', 'Methane_Emissions', 'Sea_Level_Rise', 'Arctic_Ice_Extent', 'Urbanization', 'Deforestation_Rate', 'Extreme_Weather_Events', 'Average_Rainfall', 'Solar_Energy_Potential', 'Waste_Management', 'Per_Capita_Emissions', 'Industrial_Activity', 'Air_Pollution_Index', 'Biodiversity_Index', 'Ocean_Acidification', 'Fossil_Fuel_Usage', 'Energy_Consumption_Per_Capita', 'Policy_Score', 'Average_Temperature']

In [ ]:
missing = df.isnull().sum()

missing_table = pd.DataFrame({
    "Column": df.columns,
        "Missing Values": missing.values,
            "Missing Percentage": (missing.values / len(df)) * 100
            })
display(
                missing_table.sort_values(
                        by="Missing Values",
                                ascending=False
                                    )
                                    )

                           Column  Missing Values  Missing Percentage
23  Energy_Consumption_Per_Capita            2000                 2.0
22              Fossil_Fuel_Usage            2000                 2.0
24                   Policy_Score            2000                 2.0
25            Average_Temperature            2000                 2.0
21            Ocean_Acidification            2000                 2.0
20             Biodiversity_Index            2000                 2.0
2             Temperature_Anomaly               0                 0.0
3                   CO2_Emissions               0                 0.0
0                         Country               0                 0.0
1                            Year               0                 0.0
9                  Sea_Level_Rise               0                 0.0
8               Methane_Emissions               0                 0.0
7          Renewable_Energy_Usage               0                 0.0
6                             GDP               0                 0.0
5                     Forest_Area               0                 0.0
4                      Population               0                 0.0
10              Arctic_Ice_Extent               0                 0.0
11                   Urbanization               0                 0.0
17           Per_Capita_Emissions               0                 0.0
16               Waste_Management               0                 0.0
15         Solar_Energy_Potential               0                 0.0
14               Average_Rainfall               0                 0.0
13         Extreme_Weather_Events               0                 0.0
12             Deforestation_Rate               0                 0.0
18            Industrial_Activity               0                 0.0
19            Air_Pollution_Index               0                 0.0

In [ ]:
missing_columns = [
      "Energy_Consumption_Per_Capita",
          "Fossil_Fuel_Usage",
              "Policy_Score",
                  "Average_Temperature",
                      "Ocean_Acidification",
                          "Biodiversity_Index"
                          ]
for column in missing_columns:
  print("\n" + "=" * 50)
  print(column)
  print("=" * 50)
  print("Missing by year:")
  print(
                                                      df.loc[df[column].isnull(), "Year"]
                                                              .value_counts()
                                                                      .sort_index()
                                                                          )

==================================================
Energy_Consumption_Per_Capita
==================================================
Missing by year:
Year
1900    16
1901    20
1902     9
1903    14
1904    12
        ..
2019    17
2020    18
2021    15
2022    17
2023    16
Name: count, Length: 124, dtype: int64

==================================================
Fossil_Fuel_Usage
==================================================
Missing by year:
Year
1900    19
1901    22
1902    18
1903    16
1904    15
        ..
2019    13
2020    19
2021    22
2022     8
2023    14
Name: count, Length: 124, dtype: int64

==================================================
Policy_Score
==================================================
Missing by year:
Year
1900    21
1901     9
1902    12
1903    15
1904     7
        ..
2019    18
2020     8
2021    23
2022    23
2023    23
Name: count, Length: 124, dtype: int64

==================================================
Average_Temperature
==================================================
Missing by year:
Year
1900    15
1901    13
1902    23
1903    22
1904    20
        ..
2019    14
2020    26
2021    17
2022    11
2023    16
Name: count, Length: 124, dtype: int64

==================================================
Ocean_Acidification
==================================================
Missing by year:
Year
1900    18
1901    18
1902    20
1903    16
1904    13
        ..
2019    16
2020    22
2021    20
2022    17
2023    10
Name: count, Length: 124, dtype: int64

==================================================
Biodiversity_Index
==================================================
Missing by year:
Year
1900    15
1901    13
1902    12
1903    23
1904    18
        ..
2019    12
2020    18
2021    15
2022    11
2023    13
Name: count, Length: 124, dtype: int64

In [ ]:
for column in missing_columns:
      print("\n" + "=" * 50)
      print(column)
      print("=" * 50)

      print(
                          df.loc[df[column].isnull(), "Country"]
                                  .value_counts()
                                          .head(20)
                                              )

==================================================
Energy_Consumption_Per_Capita
==================================================
Country
Country_88     20
Country_93     18
Country_150    18
Country_108    18
Country_186    18
Country_161    17
Country_118    16
Country_53     16
Country_24     16
Country_61     15
Country_117    15
Country_133    15
Country_50     15
Country_158    15
Country_170    15
Country_59     15
Country_116    15
Country_43     15
Country_192    15
Country_187    14
Name: count, dtype: int64

==================================================
Fossil_Fuel_Usage
==================================================
Country
Country_52     19
Country_12     19
Country_4      18
Country_45     17
Country_93     17
Country_76     17
Country_87     17
Country_106    16
Country_158    16
Country_119    16
Country_186    16
Country_63     15
Country_82     15
Country_47     15
Country_149    15
Country_142    14
Country_61     14
Country_26     14
Country_129    14
Country_32     14
Name: count, dtype: int64

==================================================
Policy_Score
==================================================
Country
Country_195    19
Country_36     18
Country_82     18
Country_4      17
Country_143    17
Country_104    16
Country_126    16
Country_155    16
Country_174    16
Country_8      16
Country_141    16
Country_182    16
Country_87     15
Country_20     15
Country_131    15
Country_101    15
Country_100    15
Country_83     15
Country_9      15
Country_24     15
Name: count, dtype: int64

==================================================
Average_Temperature
==================================================
Country
Country_180    20
Country_23     20
Country_50     19
Country_139    18
Country_195    18
Country_115    18
Country_147    18
Country_69     17
Country_95     17
Country_104    16
Country_59     15
Country_109    15
Country_132    15
Country_72     15
Country_126    15
Country_168    15
Country_131    15
Country_11     15
Country_79     15
Country_96     15
Name: count, dtype: int64

==================================================
Ocean_Acidification
==================================================
Country
Country_97     18
Country_10     18
Country_115    18
Country_18     17
Country_178    17
Country_168    17
Country_141    17
Country_110    16
Country_52     16
Country_131    16
Country_143    16
Country_29     15
Country_145    15
Country_78     15
Country_32     15
Country_79     15
Country_37     15
Country_149    14
Country_153    14
Country_112    14
Name: count, dtype: int64

==================================================
Biodiversity_Index
==================================================
Country
Country_176    21
Country_173    20
Country_59     20
Country_52     19
Country_27     18
Country_45     17
Country_147    16
Country_48     16
Country_156    16
Country_163    16
Country_113    16
Country_128    16
Country_29     16
Country_108    15
Country_118    15
Country_184    14
Country_57     14
Country_162    14
Country_103    14
Country_17     14
Name: count, dtype: int64

In [ ]:
missing_columns = [
      "Energy_Consumption_Per_Capita",
          "Fossil_Fuel_Usage",
              "Policy_Score",
                  "Average_Temperature",
                      "Ocean_Acidification",
                          "Biodiversity_Index"
                          ]

for column in missing_columns:
    median_value = df[column].median()
    df[column] = df[column].fillna(median_value)
print("Missing values filled successfully!")

Missing values filled successfully!

In [ ]:
print(df[missing_columns].isnull().sum())

Energy_Consumption_Per_Capita    0
Fossil_Fuel_Usage                0
Policy_Score                     0
Average_Temperature              0
Ocean_Acidification              0
Biodiversity_Index               0
dtype: int64

In [ ]:
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

In [ ]:
numeric_columns = df.select_dtypes(include="number").columns

summary = df[numeric_columns].describe().T

display(
    summary[
            ["min", "max", "mean", "50%", "std"]
                ]
                )

,min,max,mean,50%,std
Year,1.900000e+03,2.023000e+03,1.961422e+03,1.961000e+03,3.575880e+01
Temperature_Anomaly,-1.999981e+00,1.999958e+00,2.647292e-03,3.523434e-03,1.154579e+00
CO2_Emissions,1.022271e+05,9.999793e+08,5.007007e+08,5.006769e+08,2.887388e+08
Population,1.013054e+06,1.499992e+09,7.501973e+08,7.499212e+08,4.328709e+08
Forest_Area,5.188446e-05,9.999983e+01,5.001241e+01,5.014126e+01,2.880629e+01
GDP,1.524737e+08,9.999894e+12,4.995923e+12,4.985849e+12,2.883117e+12
Renewable_Energy_Usage,5.306081e-03,9.999949e+01,5.011566e+01,5.001158e+01,2.884149e+01
Methane_Emissions,1.133254e+03,9.999928e+06,5.003713e+06,4.997724e+06,2.887606e+06
Sea_Level_Rise,-4.999954e+00,4.999768e+01,2.256805e+01,2.272842e+01,1.590816e+01
Arctic_Ice_Extent,1.000036e+00,1.499988e+01,8.003934e+00,7.999331e+00,4.039130e+00
Urbanization,5.058923e-05,9.999978e+01,4.991876e+01,4.978224e+01,2.884595e+01
Deforestation_Rate,6.268523e-05,4.999960e+00,2.494102e+00,2.488219e+00,1.441101e+00
Extreme_Weather_Events,0.000000e+00,4.900000e+01,2.451986e+01,2.500000e+01,1.444272e+01
Average_Rainfall,5.000145e+02,4.999821e+03,2.750708e+03,2.750194e+03,1.295031e+03
Solar_Energy_Potential,5.000209e+02,2.499981e+03,1.496453e+03,1.497831e+03,5.764837e+02
Waste_Management,3.774576e-05,9.999994e+01,5.000979e+01,4.990350e+01,2.889085e+01
Per_Capita_Emissions,4.018352e-04,1.999983e+01,9.969773e+00,9.921851e+00,5.757802e+00
Industrial_Activity,2.978661e-03,9.999913e+01,5.010354e+01,5.012098e+01,2.891304e+01
Air_Pollution_Index,1.419316e-03,2.999926e+02,1.496277e+02,1.495081e+02,8.659966e+01
Biodiversity_Index,1.155204e-03,9.999957e+01,4.998345e+01,5.009752e+01,2.857389e+01
Ocean_Acidification,7.500007e+00,8.499991e+00,8.000406e+00,8.001393e+00,2.857538e-01
Fossil_Fuel_Usage,6.882267e-04,9.999979e+01,4.999826e+01,5.001281e+01,2.860974e+01
Energy_Consumption_Per_Capita,1.000313e+02,4.999981e+03,2.547965e+03,2.546616e+03,1.402260e+03
Policy_Score,3.097640e-03,9.999962e+01,4.998739e+01,4.995715e+01,2.854723e+01
Average_Temperature,-9.999950e+00,3.999884e+01,1.503299e+01,1.503210e+01,1.428585e+01

In [ ]:
numeric_columns = df.select_dtypes(include="number").columns

outlier_summary = []

for column in numeric_columns:
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = (
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ).sum()

    outlier_summary.append({
        "Column": column,
        "Q1": Q1,
        "Q3": Q3,
        "IQR": IQR,
        "Lower Limit": lower_limit,
        "Upper Limit": upper_limit,
        "Outliers": outliers,
        "Outlier %": (outliers / len(df)) * 100
    })

# Build and display the summary once, after every column has been checked
outlier_table = pd.DataFrame(outlier_summary)

display(
    outlier_table.sort_values(
        "Outliers",
        ascending=False
    )
)

  Column      Q1      Q3   IQR  Lower Limit  Upper Limit  Outliers  Outlier %
0   Year  1930.0  1992.0  62.0       1837.0       2085.0         0        0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1930.000000,1992.000000,62.000000,1837.000000,2085.000000,0,0.0
1,Temperature_Anomaly,-0.999449,0.998067,1.997516,-3.995723,3.994341,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0
18,Air_Pollution_Index,7.472756e+01,2.246331e+02,1.499055e+02,-1.501307e+02,4.494914e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0
18,Air_Pollution_Index,7.472756e+01,2.246331e+02,1.499055e+02,-1.501307e+02,4.494914e+02,0,0.0
19,Biodiversity_Index,2.544019e+01,7.430972e+01,4.886953e+01,-4.786410e+01,1.476140e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0
18,Air_Pollution_Index,7.472756e+01,2.246331e+02,1.499055e+02,-1.501307e+02,4.494914e+02,0,0.0
19,Biodiversity_Index,2.544019e+01,7.430972e+01,4.886953e+01,-4.786410e+01,1.476140e+02,0,0.0
20,Ocean_Acidification,7.755289e+00,8.243818e+00,4.885294e-01,7.022495e+00,8.976612e+00,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0
18,Air_Pollution_Index,7.472756e+01,2.246331e+02,1.499055e+02,-1.501307e+02,4.494914e+02,0,0.0
19,Biodiversity_Index,2.544019e+01,7.430972e+01,4.886953e+01,-4.786410e+01,1.476140e+02,0,0.0
20,Ocean_Acidification,7.755289e+00,8.243818e+00,4.885294e-01,7.022495e+00,8.976612e+00,0,0.0
21,Fossil_Fuel_Usage,2.545571e+01,7.455340e+01,4.909769e+01,-4.819082e+01,1.481999e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0
18,Air_Pollution_Index,7.472756e+01,2.246331e+02,1.499055e+02,-1.501307e+02,4.494914e+02,0,0.0
19,Biodiversity_Index,2.544019e+01,7.430972e+01,4.886953e+01,-4.786410e+01,1.476140e+02,0,0.0
20,Ocean_Acidification,7.755289e+00,8.243818e+00,4.885294e-01,7.022495e+00,8.976612e+00,0,0.0
21,Fossil_Fuel_Usage,2.545571e+01,7.455340e+01,4.909769e+01,-4.819082e+01,1.481999e+02,0,0.0
22,Energy_Consumption_Per_Capita,1.344217e+03,3.748594e+03,2.404377e+03,-2.262349e+03,7.355160e+03,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0
18,Air_Pollution_Index,7.472756e+01,2.246331e+02,1.499055e+02,-1.501307e+02,4.494914e+02,0,0.0
19,Biodiversity_Index,2.544019e+01,7.430972e+01,4.886953e+01,-4.786410e+01,1.476140e+02,0,0.0
20,Ocean_Acidification,7.755289e+00,8.243818e+00,4.885294e-01,7.022495e+00,8.976612e+00,0,0.0
21,Fossil_Fuel_Usage,2.545571e+01,7.455340e+01,4.909769e+01,-4.819082e+01,1.481999e+02,0,0.0
22,Energy_Consumption_Per_Capita,1.344217e+03,3.748594e+03,2.404377e+03,-2.262349e+03,7.355160e+03,0,0.0
23,Policy_Score,2.554935e+01,7.441044e+01,4.886109e+01,-4.774228e+01,1.477021e+02,0,0.0

,Column,Q1,Q3,IQR,Lower Limit,Upper Limit,Outliers,Outlier %
0,Year,1.930000e+03,1.992000e+03,6.200000e+01,1.837000e+03,2.085000e+03,0,0.0
1,Temperature_Anomaly,-9.994490e-01,9.980670e-01,1.997516e+00,-3.995723e+00,3.994341e+00,0,0.0
2,CO2_Emissions,2.504223e+08,7.506318e+08,5.002095e+08,-4.998919e+08,1.500946e+09,0,0.0
3,Population,3.762545e+08,1.125222e+09,7.489676e+08,-7.471969e+08,2.248673e+09,0,0.0
4,Forest_Area,2.496040e+01,7.489830e+01,4.993790e+01,-4.994645e+01,1.498051e+02,0,0.0
5,GDP,2.507503e+12,7.489082e+12,4.981579e+12,-4.964866e+12,1.496145e+13,0,0.0
6,Renewable_Energy_Usage,2.530224e+01,7.509594e+01,4.979370e+01,-4.938831e+01,1.497865e+02,0,0.0
7,Methane_Emissions,2.501312e+06,7.507855e+06,5.006542e+06,-5.008501e+06,1.501767e+07,0,0.0
8,Sea_Level_Rise,8.739127e+00,3.633315e+01,2.759402e+01,-3.265191e+01,7.772419e+01,0,0.0
9,Arctic_Ice_Extent,4.504867e+00,1.149950e+01,6.994635e+00,-5.987086e+00,2.199146e+01,0,0.0
10,Urbanization,2.499012e+01,7.485959e+01,4.986948e+01,-4.981410e+01,1.496638e+02,0,0.0
11,Deforestation_Rate,1.242782e+00,3.742646e+00,2.499864e+00,-2.507014e+00,7.492443e+00,0,0.0
12,Extreme_Weather_Events,1.200000e+01,3.700000e+01,2.500000e+01,-2.550000e+01,7.450000e+01,0,0.0
13,Average_Rainfall,1.633901e+03,3.872379e+03,2.238478e+03,-1.723815e+03,7.230095e+03,0,0.0
14,Solar_Energy_Potential,9.972655e+02,1.994097e+03,9.968313e+02,-4.979813e+02,3.489344e+03,0,0.0
15,Waste_Management,2.511462e+01,7.507269e+01,4.995808e+01,-4.982250e+01,1.500098e+02,0,0.0
16,Per_Capita_Emissions,5.020629e+00,1.495875e+01,9.938124e+00,-9.886557e+00,2.986594e+01,0,0.0
17,Industrial_Activity,2.506213e+01,7.528000e+01,5.021787e+01,-5.026467e+01,1.506068e+02,0,0.0
18,Air_Pollution_Index,7.472756e+01,2.246331e+02,1.499055e+02,-1.501307e+02,4.494914e+02,0,0.0
19,Biodiversity_Index,2.544019e+01,7.430972e+01,4.886953e+01,-4.786410e+01,1.476140e+02,0,0.0
20,Ocean_Acidification,7.755289e+00,8.243818e+00,4.885294e-01,7.022495e+00,8.976612e+00,0,0.0
21,Fossil_Fuel_Usage,2.545571e+01,7.455340e+01,4.909769e+01,-4.819082e+01,1.481999e+02,0,0.0
22,Energy_Consumption_Per_Capita,1.344217e+03,3.748594e+03,2.404377e+03,-2.262349e+03,7.355160e+03,0,0.0
23,Policy_Score,2.554935e+01,7.441044e+01,4.886109e+01,-4.774228e+01,1.477021e+02,0,0.0
24,Average_Temperature,2.814532e+00,2.726446e+01,2.444992e+01,-3.386035e+01,6.393934e+01,0,0.0

In [ ]:
outliers_only = outlier_table[
      outlier_table["Outliers"] > 0
      ].sort_values(
          "Outliers",
              ascending=False
              )

In [ ]:
print("Negative values check:")
print()

checks = {
    "Population": (df["Population"] < 0).sum(),
        "CO2_Emissions": (df["CO2_Emissions"] < 0).sum(),
            "Forest_Area": (df["Forest_Area"] < 0).sum(),
                "GDP": (df["GDP"] < 0).sum(),
                    "Renewable_Energy_Usage": (df["Renewable_Energy_Usage"] < 0).sum(),
                        "Methane_Emissions": (df["Methane_Emissions"] < 0).sum(),
                            "Average_Rainfall": (df["Average_Rainfall"] < 0).sum(),
                                "Solar_Energy_Potential": (df["Solar_Energy_Potential"] < 0).sum(),
                                    "Waste_Management": (df["Waste_Management"] < 0).sum(),
                                        "Per_Capita_Emissions": (df["Per_Capita_Emissions"] < 0).sum(),
                                            "Industrial_Activity": (df["Industrial_Activity"] < 0).sum(),
                                                "Air_Pollution_Index": (df["Air_Pollution_Index"] < 0).sum(),
                                                    "Biodiversity_Index": (df["Biodiversity_Index"] < 0).sum(),
                                                        "Fossil_Fuel_Usage": (df["Fossil_Fuel_Usage"] < 0).sum(),
                                                            "Energy_Consumption_Per_Capita": (df["Energy_Consumption_Per_Capita"] < 0).sum(),
                                                                "Policy_Score": (df["Policy_Score"] < 0).sum()
                                                                }

for column, count in checks.items():
  print(f"{column}: {count}")

Negative values check:

Population: 0
CO2_Emissions: 0
Forest_Area: 0
GDP: 0
Renewable_Energy_Usage: 0
Methane_Emissions: 0
Average_Rainfall: 0
Solar_Energy_Potential: 0
Waste_Management: 0
Per_Capita_Emissions: 0
Industrial_Activity: 0
Air_Pollution_Index: 0
Biodiversity_Index: 0
Fossil_Fuel_Usage: 0
Energy_Consumption_Per_Capita: 0
Policy_Score: 0

In [ ]:
percentage_columns = [
      "Forest_Area",
          "Renewable_Energy_Usage",
              "Urbanization",
                  "Waste_Management",
                      "Industrial_Activity",
                          "Biodiversity_Index",
                              "Fossil_Fuel_Usage",
                                  "Policy_Score"
                                  ]
for column in percentage_columns:
  below_zero = (df[column] < 0).sum()
  above_hundred = (df[column] > 100).sum()

  print(f"\n{column}")
  print("Below 0:", below_zero)
  print("Above 100:", above_hundred)

Forest_Area
Below 0: 0
Above 100: 0

Renewable_Energy_Usage
Below 0: 0
Above 100: 0

Urbanization
Below 0: 0
Above 100: 0

Waste_Management
Below 0: 0
Above 100: 0

Industrial_Activity
Below 0: 0
Above 100: 0

Biodiversity_Index
Below 0: 0
Above 100: 0

Fossil_Fuel_Usage
Below 0: 0
Above 100: 0

Policy_Score
Below 0: 0
Above 100: 0

In [ ]:
print("Minimum Year:", df["Year"].min())
print("Maximum Year:", df["Year"].max())

print("\nNumber of unique years:", df["Year"].nunique())

print("\nMissing years:")

all_years = set(range(
    df["Year"].min(),
        df["Year"].max() + 1
        ))

existing_years = set(df["Year"].unique())

missing_years = sorted(all_years - existing_years)
print(missing_years)

Minimum Year: 1900
Maximum Year: 2023

Number of unique years: 124

Missing years:
[]

In [ ]:
print("Missing Country values:", df["Country"].isnull().sum())

print("Number of unique countries:", df["Country"].nunique())

print("Leading/trailing spaces:",
      (df["Country"] != df["Country"].str.strip()).sum())

Missing Country values: 0
Number of unique countries: 195
Leading/trailing spaces: 0

In [ ]:
# Save the cleaned dataset
df.to_csv("Climate_Cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")
print("Final shape:", df.shape)
print("Total missing values:", df.isnull().sum().sum())
print("Total duplicate rows:", df.duplicated().sum())

Cleaned dataset saved successfully!
Final shape: (100000, 26)
Total missing values: 0
Total duplicate rows: 0

In [ ]:
df.to_csv("Global_Warming_Cleaned.csv", index=False)

In [ ]:
from google.colab import files

files.download("Global_Warming_Cleaned.csv")